import { Dimensions, Platform, StyleSheet } from "react-native";
import { ThemeColors } from "../constants/theme";

export const createHomeStyles = (theme: ThemeColors) => StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.background },

  // Top Header
  topHeader: {
    backgroundColor: theme.cardBg,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderColor: theme.border,
    zIndex: 10,
  },
  brandRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  brandLogo: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  onlineDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#10B981' },
  brandTitle: { fontSize: 20, fontWeight: '900', color: theme.textPrimary, letterSpacing: -0.5 },

  modeSwitchPill: {
    flexDirection: 'row',
    backgroundColor: theme.surfaceElevated,
    borderRadius: 20,
    padding: 3,
    borderWidth: 1,
    borderColor: theme.border,
  },
  modePillBtn: { paddingVertical: 4, paddingHorizontal: 8, borderRadius: 16 },
  modePillBtnActive: { backgroundColor: '#10B981' },
  modePillText: { fontSize: 11, fontWeight: '700', color: theme.textSecondary },
  modePillTextActive: { color: '#070A0F' },

  pilotBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: theme.badgeBg,
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.badgeBorder,
  },
  pilotBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#10B981',
    letterSpacing: 0.2,
  },

  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  sosShieldBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: theme.sosRedSurface,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.4)',
  },
  sosShieldText: { color: '#EF4444', fontSize: 11, fontWeight: '800' },
  walletBadge: {
    backgroundColor: theme.badgeBg,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.badgeBorder,
  },
  walletBadgeText: { color: '#10B981', fontSize: 11, fontWeight: '800' },
  logoutHeaderBtn: {
    backgroundColor: theme.sosRedSurface,
    paddingHorizontal: 7,
    paddingVertical: 5,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Map Viewport
  mapViewport: { height: Dimensions.get('window').height * 0.42, backgroundColor: theme.background, overflow: 'hidden' },
  mapCanvas: { flex: 1, backgroundColor: theme.background, position: 'relative' },
  highwayLine: {
    position: 'absolute',
    height: 8,
    backgroundColor: '#161F33',
    borderColor: theme.border,
    borderWidth: 1,
  },
  streetLabel: {
    position: 'absolute',
    color: '#334155',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 2,
  },
  floatingEtaPill: {
    position: 'absolute',
    top: 14,
    left: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: theme.cardBg,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.badgeBorder,
    elevation: 8,
  },
  floatingEtaText: { color: theme.textPrimary, fontSize: 11, fontWeight: '700' },
  recenterMapBtn: {
    position: 'absolute',
    top: 14,
    right: 16,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.cardBg,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.cardBorder,
    elevation: 8,
  },

  // Map Markers
  mapMarker: { position: 'absolute', alignItems: 'center', justifyContent: 'center' },
  userBeaconMarker: { left: '46%', top: '44%' },
  userBeaconPulse: {
    position: 'absolute',
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.badgeBg,
  },
  userBeaconDot: { width: 14, height: 14, borderRadius: 7, backgroundColor: '#10B981', borderWidth: 2, borderColor: '#FFF' },
  beaconCallout: {
    position: 'absolute',
    top: 20,
    backgroundColor: theme.cardBg,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.cardBorder,
  },
  beaconCalloutText: { color: theme.textPrimary, fontSize: 10, fontWeight: '700' },

  destinationMarker: { left: '72%', top: '28%' },
  destPinOuter: { width: 26, height: 26, borderRadius: 13, backgroundColor: '#F59E0B', alignItems: 'center', justifyContent: 'center' },

  driverMapMarker: { zIndex: 5 },
  driverMarkerBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: theme.cardBg,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#10B981',
  },
  driverMarkerSpeed: { color: '#10B981', fontSize: 10, fontWeight: '800' },

  idleDriverMarker: { zIndex: 4 },
  idleDriverPill: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: theme.surfaceElevated,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  routePolylineGlow: {
    position: 'absolute',
    top: '32%',
    left: '48%',
    width: '28%',
    height: 3,
    backgroundColor: '#10B981',
    transform: [{ rotate: '-25deg' }],
  },

  // Bottom Sheet
  bottomSheet: { flex: 1, backgroundColor: theme.background },
  bottomSheetContent: { padding: 16 },

  // Idle Screen
  serviceTilesRow: { flexDirection: 'row', gap: 12, marginBottom: 16 },
  serviceTile: {
    flex: 1,
    backgroundColor: theme.cardBg,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.border,
  },
  serviceTileActive: { borderColor: '#10B981' },
  serviceTileIcon: { marginBottom: 8 },
  serviceTileTitle: { color: theme.textPrimary, fontSize: 15, fontWeight: '800' },
  serviceTileSub: { color: theme.textSecondary, fontSize: 11, marginTop: 2 },

  whereToSearchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.cardBg,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: theme.cardBorder,
    marginBottom: 20,
  },
  whereToPlaceholder: { flex: 1, color: theme.textSecondary, fontSize: 16, fontWeight: '600' },
  nowBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: theme.surfaceElevated,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
  },
  nowBadgeText: { color: theme.textPrimary, fontSize: 12, fontWeight: '700' },

  sectionHeader: { color: theme.textSecondary, fontSize: 12, fontWeight: '800', letterSpacing: 1, marginBottom: 12, textTransform: 'uppercase' },
  placesList: { gap: 10 },
  placeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.cardBg,
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.border,
  },
  placeIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: theme.badgeBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  placeInfo: { flex: 1 },
  placeName: { color: theme.textPrimary, fontSize: 14, fontWeight: '700' },
  placeAddress: { color: theme.textSecondary, fontSize: 11, marginTop: 2 },
  placeEta: { color: '#10B981', fontSize: 12, fontWeight: '700' },

  // Vehicle Selection Sheet
  idleSearchSheet: { gap: 14 },
  selectionSheet: { gap: 14 },
  destinationSelectedBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.cardBg,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#10B981',
  },
  destSelectedTitle: { color: theme.textPrimary, fontSize: 15, fontWeight: '800' },
  destSelectedAddress: { color: theme.textSecondary, fontSize: 12, marginTop: 2 },
  changeDestBtn: { padding: 4 },

  categoryList: { gap: 10 },
  categoryCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.cardBg,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.border,
  },
  categoryCardSelected: { borderColor: '#10B981', backgroundColor: 'rgba(16, 185, 129, 0.06)' },
  categoryIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.surfaceElevated,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  categoryIconCircleSelected: { backgroundColor: theme.badgeBg },
  categoryInfo: { flex: 1 },
  categoryName: { color: theme.textPrimary, fontSize: 15, fontWeight: '800' },
  capacityBadge: { flexDirection: 'row', alignItems: 'center', gap: 2, backgroundColor: theme.surfaceElevated, paddingHorizontal: 5, paddingVertical: 2, borderRadius: 8 },
  capacityText: { color: theme.textSecondary, fontSize: 10, fontWeight: '700' },
  categoryEta: { color: '#10B981', fontSize: 11, fontWeight: '700' },
  categorySub: { color: theme.textSecondary, fontSize: 11, marginTop: 2 },
  categoryPriceBox: { alignItems: 'flex-end' },
  categoryPriceText: { color: theme.textPrimary, fontSize: 16, fontWeight: '900' },

  paymentSelectorRow: { flexDirection: 'row', gap: 10, marginTop: 4 },
  paymentMethodChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: theme.cardBg,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
    flex: 1,
  },
  paymentMethodText: { color: theme.textPrimary, fontSize: 12, fontWeight: '700', flex: 1 },
  promoCodeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: theme.cardBg,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.3)',
  },
  promoCodeText: { color: '#F59E0B', fontSize: 12, fontWeight: '700' },

  confirmRideButton: {
    backgroundColor: '#10B981',
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 6,
    elevation: 8,
  },
  confirmRideButtonText: { color: '#070A0F', fontSize: 16, fontWeight: '900', letterSpacing: 0.3 },

  // Searching State (Radar Dispatch)
  searchingCard: {
    backgroundColor: theme.cardBg,
    borderRadius: 20,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.badgeBorder,
  },
  radarWaveOuter: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: theme.badgeBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  radarWaveInner: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(16, 185, 129, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchingTitle: { color: theme.textPrimary, fontSize: 18, fontWeight: '900', marginBottom: 4 },
  searchingSubtitle: { color: theme.textSecondary, fontSize: 12, textAlign: 'center', marginBottom: 16 },
  searchingProgressBar: {
    width: '100%',
    height: 4,
    backgroundColor: theme.surfaceElevated,
    borderRadius: 2,
    overflow: 'hidden',
    marginBottom: 16,
  },
  searchingProgressFill: { width: '70%', height: '100%', backgroundColor: '#10B981' },
  searchingDetailsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingVertical: 10,
    borderTopWidth: 1,
    borderColor: theme.border,
    marginBottom: 16,
  },
  searchingDetailText: { color: theme.textSecondary, fontSize: 12, fontWeight: '600' },
  cancelSearchBtn: {
    width: '100%',
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.5)',
    alignItems: 'center',
  },
  cancelSearchBtnText: { color: '#EF4444', fontSize: 13, fontWeight: '800' },

  // Active Ride Sheet
  activeRideSheet: { gap: 14 },
  statusBarRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 4 },
  statusPulseDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#10B981' },
  statusTitle: { color: '#10B981', fontSize: 13, fontWeight: '800' },

  driverProfileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.cardBg,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.border,
  },
  driverAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: theme.surfaceElevated,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  driverMeta: { flex: 1 },
  driverName: { color: theme.textPrimary, fontSize: 16, fontWeight: '800' },
  driverSub: { color: theme.textSecondary, fontSize: 12, marginTop: 2 },
  ratingRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4 },
  ratingText: { color: '#F59E0B', fontSize: 11, fontWeight: '700' },
  plateBadge: {
    backgroundColor: theme.surfaceElevated,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  plateText: { color: theme.textPrimary, fontSize: 13, fontWeight: '900', letterSpacing: 1 },

  // Safety PIN
  safetyPinCard: {
    backgroundColor: theme.cardBg,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.badgeBorder,
    alignItems: 'center',
  },
  safetyPinHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 },
  safetyPinTitle: { color: '#10B981', fontSize: 13, fontWeight: '800' },
  safetyPinDesc: { color: theme.textSecondary, fontSize: 11, textAlign: 'center', marginBottom: 12 },
  pinDigitsRow: { flexDirection: 'row', gap: 12 },
  pinDigitBox: {
    width: 46,
    height: 52,
    borderRadius: 12,
    backgroundColor: theme.background,
    borderWidth: 2,
    borderColor: '#10B981',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinDigitText: { color: theme.textPrimary, fontSize: 24, fontWeight: '900' },

  routeLocationsCard: {
    backgroundColor: theme.cardBg,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.border,
  },
  routePointRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  routeDot: { width: 10, height: 10, borderRadius: 5 },
  routeConnectorLine: { width: 2, height: 14, backgroundColor: '#334155', marginLeft: 4, marginVertical: 2 },
  routePointText: { color: theme.textPrimary, fontSize: 12, fontWeight: '600', flex: 1 },

  tripActionsGrid: { flexDirection: 'row', gap: 8 },
  callDriverBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: theme.surfaceElevated,
    paddingVertical: 12,
    borderRadius: 14,
  },
  callDriverText: { color: theme.textPrimary, fontSize: 12, fontWeight: '700' },
  messageDriverBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: theme.surfaceElevated,
    paddingVertical: 12,
    borderRadius: 14,
  },
  messageDriverText: { color: theme.textPrimary, fontSize: 12, fontWeight: '700' },
  shareTripBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: theme.badgeBg,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.badgeBorder,
  },
  shareTripText: { color: '#10B981', fontSize: 12, fontWeight: '700' },
  cancelTripBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  cancelTripText: { color: '#EF4444', fontSize: 12, fontWeight: '700' },

  recipientBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.25)',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 8,
  },
  recipientBadgeText: { color: theme.textSecondary, fontSize: 12 },

  riderSelectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 8,
  },
  riderSelectorPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: theme.cardBg,
    borderWidth: 1,
    borderColor: theme.cardBorder,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  riderSelectorPillText: { color: theme.textPrimary, fontSize: 12, fontWeight: '700' },
  resetRiderBtn: { paddingVertical: 4, paddingHorizontal: 8 },
  resetRiderBtnText: { color: '#EF4444', fontSize: 11, fontWeight: '700' },

  riderModalCard: {
    backgroundColor: theme.cardBg,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 36,
    gap: 14,
  },
  riderModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  riderModalTitle: { color: '#FFFFFF', fontSize: 20, fontWeight: '900' },
  riderOptionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.surfaceActive,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.border,
  },
  riderOptionCardOther: {
    backgroundColor: theme.surfaceActive,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.border,
  },
  riderOptionCardSelected: {
    borderColor: '#10B981',
    backgroundColor: 'rgba(16, 185, 129, 0.06)',
  },
  riderOptionAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.badgeBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  riderOptionName: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' },
  riderOptionSub: { color: theme.textSecondary, fontSize: 12, marginTop: 2 },
  otherRiderInput: {
    backgroundColor: theme.background,
    borderWidth: 1,
    borderColor: theme.cardBorder,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: theme.textPrimary,
    fontSize: 14,
  },
  presetRidersRow: { flexDirection: 'row', gap: 8 },
  presetRiderChip: {
    backgroundColor: theme.background,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: theme.border,
  },
  presetRiderText: { color: theme.textSecondary, fontSize: 11 },
  saveOtherRiderBtn: {
    backgroundColor: '#10B981',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  saveOtherRiderBtnText: { color: '#070A0F', fontSize: 14, fontWeight: '900' },

  simulateArrivedBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: theme.badgeBg,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#10B981',
    marginTop: 6,
  },
  simulateArrivedText: { color: '#10B981', fontSize: 13, fontWeight: '800' },

  // Driver Mode
  driverSheet: { gap: 14 },
  driverEarningsCard: {
    backgroundColor: theme.cardBg,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.border,
  },
  driverEarningsTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  earningsLabel: { color: theme.textSecondary, fontSize: 10, fontWeight: '800', letterSpacing: 1 },
  earningsValue: { color: theme.textPrimary, fontSize: 24, fontWeight: '900', marginTop: 2 },
  tripsCountBadge: { backgroundColor: theme.surfaceElevated, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12, alignItems: 'center' },
  tripsCountNumber: { color: '#10B981', fontSize: 16, fontWeight: '900' },
  tripsCountLabel: { color: theme.textSecondary, fontSize: 10, fontWeight: '600' },

  driverStatsRow: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', marginTop: 14, paddingTop: 14, borderTopWidth: 1, borderColor: theme.border },
  statCol: { alignItems: 'center' },
  statColVal: { color: theme.textPrimary, fontSize: 13, fontWeight: '800' },
  statColLabel: { color: theme.textSecondary, fontSize: 10, marginTop: 2 },
  statDivider: { width: 1, height: 24, backgroundColor: 'rgba(255, 255, 255, 0.08)' },

  goButtonContainer: { alignItems: 'center', marginVertical: 10 },
  giantGoButton: {
    width: 120,
    height: 120,
    borderRadius: 60,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 15,
  },
  giantGoOnline: { backgroundColor: '#10B981', borderWidth: 4, borderColor: 'rgba(16, 185, 129, 0.4)' },
  giantGoOffline: { backgroundColor: theme.surfaceElevated, borderWidth: 4, borderColor: '#334155' },
  giantGoText: { color: theme.textPrimary, fontSize: 28, fontWeight: '900', letterSpacing: 1 },
  giantGoSubtext: { color: 'rgba(255, 255, 255, 0.8)', fontSize: 10, fontWeight: '700', marginTop: 2 },

  incomingOfferCard: {
    backgroundColor: theme.cardBg,
    borderRadius: 18,
    padding: 18,
    borderWidth: 2,
    borderColor: '#F59E0B',
    gap: 12,
  },
  incomingOfferHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  countdownBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(245, 158, 11, 0.15)', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  countdownText: { color: '#F59E0B', fontSize: 12, fontWeight: '800' },
  incomingOfferPrice: { color: '#10B981', fontSize: 20, fontWeight: '900' },
  incomingRiderRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  riderAvatarCircle: { width: 36, height: 36, borderRadius: 18, backgroundColor: theme.surfaceElevated, alignItems: 'center', justifyContent: 'center' },
  incomingRiderName: { color: theme.textPrimary, fontSize: 14, fontWeight: '800' },
  incomingRiderRating: { color: '#F59E0B', fontSize: 11, fontWeight: '700' },
  incomingRouteBox: { backgroundColor: theme.background, padding: 12, borderRadius: 12, gap: 6 },
  incomingRouteText: { color: theme.textSecondary, fontSize: 12, fontWeight: '600' },
  offerButtonsRow: { flexDirection: 'row', gap: 10 },
  declineOfferBtn: { flex: 1, paddingVertical: 12, borderRadius: 12, backgroundColor: theme.surfaceElevated, alignItems: 'center' },
  declineOfferText: { color: theme.textSecondary, fontSize: 13, fontWeight: '700' },
  acceptOfferBtn: { flex: 2, paddingVertical: 12, borderRadius: 12, backgroundColor: '#10B981', alignItems: 'center' },
  acceptOfferText: { color: '#070A0F', fontSize: 14, fontWeight: '900' },

  driverActiveTripCard: { backgroundColor: theme.cardBg, borderRadius: 16, padding: 16, gap: 10, borderWidth: 1, borderColor: '#10B981' },
  driverTripHeader: { color: '#10B981', fontSize: 11, fontWeight: '800', letterSpacing: 0.5 },
  driverPassengerText: { color: theme.textPrimary, fontSize: 14, fontWeight: '700' },
  driverDestinationText: { color: theme.textSecondary, fontSize: 12 },
  driverActionBtnGreen: { backgroundColor: '#10B981', borderRadius: 12, paddingVertical: 14, alignItems: 'center', marginTop: 6 },
  driverActionBtnBlue: { backgroundColor: '#3B82F6', borderRadius: 12, paddingVertical: 14, alignItems: 'center', marginTop: 6 },
  driverActionBtnText: { color: theme.textPrimary, fontSize: 14, fontWeight: '800' },
  pinVerifySection: { gap: 8, marginTop: 4 },
  pinVerifyPrompt: { color: theme.textPrimary, fontSize: 12, fontWeight: '600' },
  pinVerifyInput: {
    backgroundColor: theme.background,
    borderWidth: 1,
    borderColor: theme.cardBorder,
    borderRadius: 10,
    color: theme.textPrimary,
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
    paddingVertical: 10,
  },

  // Modals
  searchModalContainer: { flex: 1, backgroundColor: theme.background },
  searchModalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingBottom: 14 },
  searchBackBtn: { padding: 4 },
  searchModalTitle: { color: theme.textPrimary, fontSize: 18, fontWeight: '800' },
  searchInputsContainer: {
    backgroundColor: theme.cardBg,
    marginHorizontal: 16,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.border,
  },
  pickupInputRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  searchDot: { width: 10, height: 10, borderRadius: 5 },
  pickupInputStatic: { color: theme.textSecondary, fontSize: 14, fontWeight: '600' },
  searchConnectorLine: { width: 2, height: 18, backgroundColor: '#334155', marginLeft: 4, marginVertical: 2 },
  destinationInputRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  destinationTextInput: { flex: 1, color: theme.textPrimary, fontSize: 15, fontWeight: '700' },
  searchResultsList: { flex: 1, paddingHorizontal: 16, marginTop: 14 },
  searchSectionLabel: { color: theme.textMuted, fontSize: 11, fontWeight: '800', letterSpacing: 1, marginBottom: 12 },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderColor: theme.border,
  },
  searchResultIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  searchResultMeta: { flex: 1 },
  searchResultName: { color: theme.textPrimary, fontSize: 14, fontWeight: '700' },
  searchResultAddress: { color: theme.textSecondary, fontSize: 11, marginTop: 2 },
  searchResultDistance: { alignItems: 'flex-end' },
  searchResultDistText: { color: '#10B981', fontSize: 12, fontWeight: '700' },
  searchResultEtaText: { color: theme.textMuted, fontSize: 11 },

  // Live Serply Place Card Styles
  placeCardContainer: {
    backgroundColor: theme.cardBg,
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: theme.border,
  },
  placeCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  placeCardThumb: {
    width: 64,
    height: 64,
    borderRadius: 12,
    backgroundColor: theme.surfaceActive,
  },
  placeCardThumbPlaceholder: {
    width: 64,
    height: 64,
    borderRadius: 12,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeCardMeta: {
    flex: 1,
  },
  placeCardName: {
    color: theme.textPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
  placeCardAddress: {
    color: theme.textSecondary,
    fontSize: 12,
    marginTop: 2,
    lineHeight: 16,
  },
  placeCardBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 6,
    marginTop: 6,
  },
  placeRatingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: 'rgba(245, 158, 11, 0.15)',
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 8,
  },
  placeRatingText: {
    color: '#F59E0B',
    fontSize: 11,
    fontWeight: '800',
  },
  placeCategoryBadge: {
    backgroundColor: theme.surfaceActive,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 8,
  },
  placeCategoryText: {
    color: theme.textMuted,
    fontSize: 11,
    fontWeight: '600',
  },
  placeHoursText: {
    color: '#10B981',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 6,
  },
  placeCardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  placeSelectBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#10B981',
    paddingVertical: 9,
    borderRadius: 10,
  },
  placeSelectBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  placeActionIconBtn: {
    paddingHorizontal: 10,
    paddingVertical: 9,
    borderRadius: 10,
    backgroundColor: theme.surfaceActive,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchStatusBox: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 32,
    paddingHorizontal: 20,
    gap: 10,
  },
  searchStatusTitle: {
    color: theme.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  searchStatusSubtitle: {
    color: theme.textMuted,
    fontSize: 12,
    textAlign: 'center',
  },
  searchRetryBtn: {
    marginTop: 6,
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
  },
  searchRetryBtnText: {
    color: '#10B981',
    fontSize: 13,
    fontWeight: '700',
  },

  // Chat Modal
  chatModalContainer: { flex: 1, backgroundColor: theme.background },
  chatModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 14,
    backgroundColor: theme.cardBg,
    borderBottomWidth: 1,
    borderColor: theme.border,
  },
  chatDriverName: { color: theme.textPrimary, fontSize: 16, fontWeight: '800' },
  chatDriverSub: { color: theme.textSecondary, fontSize: 11, marginTop: 1 },
  chatCallBtn: { padding: 8, backgroundColor: theme.badgeBg, borderRadius: 20 },
  quickRepliesRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 16, paddingVertical: 10, backgroundColor: theme.cardBg },
  quickReplyChip: { backgroundColor: theme.surfaceElevated, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12 },
  quickReplyText: { color: theme.textSecondary, fontSize: 11, fontWeight: '600' },
  chatMessagesScroll: { flex: 1 },
  chatBubble: { maxWidth: '80%', padding: 12, borderRadius: 14 },
  chatBubbleRider: { alignSelf: 'flex-end', backgroundColor: '#10B981' },
  chatBubbleDriver: { alignSelf: 'flex-start', backgroundColor: theme.surfaceElevated },
  chatText: { color: theme.textPrimary, fontSize: 13, fontWeight: '600' },
  chatTime: { color: 'rgba(255, 255, 255, 0.6)', fontSize: 9, marginTop: 4, alignSelf: 'flex-end' },
  chatInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 10,
    backgroundColor: theme.cardBg,
    gap: 10,
    borderTopWidth: 1,
    borderColor: theme.border,
  },
  chatTextInput: {
    flex: 1,
    backgroundColor: theme.background,
    borderWidth: 1,
    borderColor: theme.cardBorder,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: theme.textPrimary,
    fontSize: 13,
  },
  chatSendBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#10B981',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Payment Modal
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.75)', justifyContent: 'center', padding: 20 },
  modalOverlayDark: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.85)', justifyContent: 'center', padding: 20 },
  paymentModalCard: { backgroundColor: theme.cardBg, borderRadius: 20, padding: 20, gap: 12, borderWidth: 1, borderColor: theme.cardBorder },
  paymentModalTitle: { color: theme.textPrimary, fontSize: 18, fontWeight: '800', marginBottom: 4 },
  pmOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.background,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.border,
  },
  pmOptionRowSelected: { borderColor: '#10B981' },
  pmOptionTitle: { color: theme.textPrimary, fontSize: 14, fontWeight: '700' },
  pmOptionSub: { color: theme.textSecondary, fontSize: 11, marginTop: 2 },
  closePaymentBtn: { backgroundColor: '#10B981', paddingVertical: 14, borderRadius: 14, alignItems: 'center', marginTop: 6 },
  closePaymentBtnText: { color: '#070A0F', fontSize: 14, fontWeight: '900' },

  // Rating Modal
  ratingCard: { backgroundColor: theme.cardBg, borderRadius: 20, padding: 20, alignItems: 'center', borderWidth: 1, borderColor: theme.cardBorder, gap: 12 },
  ratingAvatarCircle: { width: 60, height: 60, borderRadius: 30, backgroundColor: theme.badgeBg, alignItems: 'center', justifyContent: 'center' },
  ratingModalTitle: { color: theme.textPrimary, fontSize: 16, fontWeight: '800', textAlign: 'center' },
  ratingModalSub: { color: theme.textSecondary, fontSize: 12 },
  starsRow: { flexDirection: 'row', gap: 10, marginVertical: 6 },
  complimentsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, justifyContent: 'center' },
  complimentChip: { backgroundColor: theme.surfaceElevated, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12 },
  complimentChipActive: { backgroundColor: '#10B981' },
  complimentText: { color: theme.textSecondary, fontSize: 11, fontWeight: '600' },
  complimentTextActive: { color: '#070A0F', fontWeight: '700' },
  tipLabel: { color: theme.textPrimary, fontSize: 13, fontWeight: '700', marginTop: 4 },
  tipButtonsRow: { flexDirection: 'row', gap: 8 },
  tipChip: { backgroundColor: theme.surfaceElevated, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12 },
  tipChipActive: { backgroundColor: '#10B981' },
  tipText: { color: theme.textPrimary, fontSize: 12, fontWeight: '700' },
  tipTextActive: { color: '#070A0F' },
  receiptBox: { width: '100%', backgroundColor: theme.background, padding: 12, borderRadius: 12, gap: 4 },
  receiptRow: { flexDirection: 'row', justifyContent: 'space-between' },
  receiptLabel: { color: theme.textSecondary, fontSize: 12 },
  receiptValue: { color: theme.textPrimary, fontSize: 12, fontWeight: '600' },
  receiptTotalLabel: { color: theme.textPrimary, fontSize: 13, fontWeight: '800' },
  receiptTotalValue: { color: '#10B981', fontSize: 14, fontWeight: '900' },
  submitRatingBtn: { width: '100%', backgroundColor: '#10B981', paddingVertical: 14, borderRadius: 14, alignItems: 'center', marginTop: 6 },
  submitRatingText: { color: '#070A0F', fontSize: 14, fontWeight: '900' },
  pdfReceiptBtn: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderWidth: 1,
    borderColor: theme.badgeBorder,
    paddingVertical: 12,
    borderRadius: 14,
    marginTop: 8,
  },
  pdfReceiptText: {
    color: '#10B981',
    fontSize: 13,
    fontWeight: '800',
  },

  // ==================== ADMIN SUITE STYLES ====================
  adminContainer: { gap: 14, paddingBottom: 24 },
  adminBanner: {
    backgroundColor: theme.cardBg,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.25)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  adminBannerLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  adminBadgeIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.badgeBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adminBannerTitle: { color: theme.textPrimary, fontSize: 15, fontWeight: '800' },
  adminBannerSub: { color: theme.textSecondary, fontSize: 11, marginTop: 2 },
  adminLivePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: theme.badgeBg,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  adminLiveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#10B981' },
  adminLiveText: { color: '#10B981', fontSize: 10, fontWeight: '900' },

  adminMetricsRow: {
    flexDirection: 'row',
    backgroundColor: theme.cardBg,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: theme.border,
    alignItems: 'center',
  },
  adminMetricCard: { flex: 1, alignItems: 'center' },
  adminMetricVal: { color: theme.textPrimary, fontSize: 16, fontWeight: '900' },
  adminMetricLabel: { color: theme.textSecondary, fontSize: 11, marginTop: 2 },
  adminMetricDivider: { width: 1, height: 26, backgroundColor: 'rgba(255, 255, 255, 0.08)' },

  adminSubTabRow: { flexDirection: 'row', gap: 6 },
  adminSubTabBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingVertical: 10,
    backgroundColor: theme.cardBg,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.border,
  },
  adminSubTabBtnActive: { backgroundColor: '#10B981', borderColor: '#10B981' },
  adminSubTabText: { color: theme.textSecondary, fontSize: 11, fontWeight: '700' },
  adminSubTabTextActive: { color: '#070A0F', fontWeight: '900' },

  adminListContainer: { gap: 10 },
  adminSectionHeader: { color: theme.textMuted, fontSize: 11, fontWeight: '800', letterSpacing: 0.5, marginTop: 4 },
  adminCard: {
    backgroundColor: theme.cardBg,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: theme.border,
    gap: 12,
  },
  adminCardTop: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  adminCardAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.badgeBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adminNameRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  adminCardTitle: { color: theme.textPrimary, fontSize: 14, fontWeight: '800' },
  adminCardSub: { color: theme.textSecondary, fontSize: 12, marginTop: 2 },

  adminStatusBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10 },
  statusBadgeApproved: { backgroundColor: theme.badgeBg },
  statusBadgePending: { backgroundColor: 'rgba(245, 158, 11, 0.15)' },
  statusBadgeRejected: { backgroundColor: theme.sosRedSurface },
  adminStatusText: { fontSize: 10, fontWeight: '800' },
  statusTextApproved: { color: '#10B981' },
  statusTextPending: { color: '#F59E0B' },
  statusTextRejected: { color: '#EF4444' },

  adminDocChecklist: {
    backgroundColor: theme.background,
    borderRadius: 12,
    padding: 10,
    gap: 8,
  },
  docCheckItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  docCheckText: { color: theme.textSecondary, fontSize: 11, flex: 1, marginLeft: 8 },
  docCheckValue: { color: theme.textPrimary, fontWeight: '700' },

  adminCardActions: { flexDirection: 'row', gap: 8, marginTop: 2 },
  adminInspectBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    backgroundColor: theme.surfaceElevated,
    paddingVertical: 10,
    borderRadius: 12,
  },
  adminInspectBtnText: { color: theme.textPrimary, fontSize: 12, fontWeight: '700' },
  adminRejectBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: theme.sosRedSurface,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  adminRejectBtnText: { color: '#EF4444', fontSize: 12, fontWeight: '700' },
  adminApproveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: '#10B981',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
  },
  adminApproveBtnText: { color: '#070A0F', fontSize: 12, fontWeight: '900' },

  adminRiderMetaRow: { flexDirection: 'row', gap: 8 },
  riderMetaChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: theme.background,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
  },
  riderMetaChipLabel: { color: theme.textMuted, fontSize: 10, fontWeight: '600' },
  riderMetaChipVal: { color: theme.textPrimary, fontSize: 11, fontWeight: '800' },
  adminFlagRiskBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    backgroundColor: 'rgba(245, 158, 11, 0.15)',
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.3)',
  },
  adminFlagRiskText: { color: '#F59E0B', fontSize: 12, fontWeight: '700' },

  txSummaryBox: {
    flexDirection: 'row',
    backgroundColor: theme.cardBg,
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: theme.border,
    alignItems: 'center',
  },
  txSummaryCol: { flex: 1, alignItems: 'center' },
  txSummaryLabel: { color: theme.textMuted, fontSize: 9, fontWeight: '800' },
  txSummaryVal: { color: theme.textPrimary, fontSize: 13, fontWeight: '900', marginTop: 3 },
  txSummaryDivider: { width: 1, height: 24, backgroundColor: 'rgba(255, 255, 255, 0.08)' },

  txPartyRow: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: theme.background, padding: 8, borderRadius: 10 },
  txPartyText: { color: theme.textSecondary, fontSize: 11 },
  txPartyBold: { color: theme.textPrimary, fontWeight: '700' },

  txBreakdownBox: { backgroundColor: theme.background, borderRadius: 10, padding: 10, gap: 5 },
  txBreakRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  txBreakLabel: { color: theme.textSecondary, fontSize: 11 },
  txBreakVal: { color: theme.textPrimary, fontSize: 11, fontWeight: '700' },

  adminReconcileBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: '#10B981',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
  },
  adminReconcileBtnText: { color: '#070A0F', fontSize: 12, fontWeight: '900' },

  // Admin Modals
  adminModalCard: {
    backgroundColor: theme.cardBg,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: '90%',
    borderWidth: 1,
    borderColor: theme.cardBorder,
  },
  adminModalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 },
  adminModalTitle: { color: theme.textPrimary, fontSize: 17, fontWeight: '800' },

  dossierProfileHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 16 },
  dossierAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: theme.badgeBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dossierDriverName: { color: theme.textPrimary, fontSize: 16, fontWeight: '800' },
  dossierDriverSub: { color: theme.textSecondary, fontSize: 12, marginTop: 2 },
  dossierVehicleBadge: { color: '#10B981', fontSize: 11, fontWeight: '700', marginTop: 2 },

  docCertPreviewCard: {
    backgroundColor: theme.background,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.badgeBorder,
    gap: 12,
  },
  docCertHeader: { borderBottomWidth: 1, borderColor: theme.border, paddingBottom: 8 },
  docCertAgency: { color: '#10B981', fontSize: 10, fontWeight: '900', letterSpacing: 0.5 },
  docCertType: { color: theme.textPrimary, fontSize: 12, fontWeight: '800', marginTop: 2 },

  docCertGrid: { gap: 10 },
  docCertItem: { backgroundColor: theme.cardBg, padding: 10, borderRadius: 10 },
  docCertLabel: { color: theme.textMuted, fontSize: 9, fontWeight: '800' },
  docCertVal: { color: theme.textPrimary, fontSize: 13, fontWeight: '800', marginTop: 2 },
  docCertStatusGreen: { color: '#10B981', fontSize: 10, fontWeight: '700', marginTop: 2 },

  docCertFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderTopWidth: 1,
    borderColor: theme.border,
    paddingTop: 8,
  },
  docCertHash: { color: theme.textMuted, fontSize: 10, fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace' },

  adminDocThumbnailCard: {
    backgroundColor: theme.background,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.cardBorder,
    padding: 8,
    alignItems: 'center',
    marginRight: 10,
    width: 108,
  },
  adminDocImage: {
    width: 92,
    height: 72,
    borderRadius: 8,
    backgroundColor: theme.surfaceActive,
  },
  adminDocThumbLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: theme.textSecondary,
    marginTop: 6,
    textAlign: 'center',
  },
  adminSaccoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.25)',
    borderRadius: 12,
    padding: 12,
    marginTop: 12,
  },
  adminSaccoTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: theme.textPrimary,
  },
  adminSaccoSub: {
    fontSize: 11,
    color: theme.textSecondary,
    marginTop: 2,
  },

  modalDecisionRow: { flexDirection: 'row', gap: 10, marginTop: 18 },
  modalRejectBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: theme.sosRedSurface,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  modalRejectText: { color: '#EF4444', fontSize: 13, fontWeight: '800' },
  modalApproveBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#10B981',
    paddingVertical: 14,
    borderRadius: 14,
  },
  modalApproveText: { color: '#070A0F', fontSize: 13, fontWeight: '900' },
  modalStatusBanner: {
    width: '100%',
    backgroundColor: theme.surfaceElevated,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  modalStatusBannerText: { color: theme.textPrimary, fontSize: 13, fontWeight: '800' },

  txAuditReceiptHeader: {
    backgroundColor: theme.background,
    borderRadius: 14,
    padding: 14,
    alignItems: 'center',
    gap: 4,
    marginBottom: 12,
  },
  txAuditMpesaBrand: { color: '#10B981', fontSize: 11, fontWeight: '900', letterSpacing: 0.5 },
  txAuditReceiptNo: { color: theme.textPrimary, fontSize: 20, fontWeight: '900', letterSpacing: 1 },
  txAuditTimestamp: { color: theme.textSecondary, fontSize: 11 },

  txAuditPayloadBox: { backgroundColor: theme.background, borderRadius: 14, padding: 12, gap: 8, marginBottom: 14 },
  txAuditRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  txAuditKey: { color: theme.textSecondary, fontSize: 12 },
  txAuditVal: { color: theme.textPrimary, fontSize: 12, fontWeight: '700' },

  modalAuditReconcileBtn: {
    backgroundColor: '#10B981',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 14,
    borderRadius: 14,
  },
  modalAuditReconcileText: { color: '#070A0F', fontSize: 14, fontWeight: '900' },

  // Locked mode pill button
  modePillBtnLocked: { opacity: 0.75 },
  modePillTextLocked: { color: theme.textSecondary, fontSize: 10 },

  // Driver Status Banners
  driverStatusBannerPending: {
    backgroundColor: 'rgba(245, 158, 11, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.35)',
    borderRadius: 16,
    padding: 12,
    marginBottom: 12,
    gap: 10,
  },
  statusBannerLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  statusBannerIconPending: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(245, 158, 11, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusBannerTitlePending: { color: '#FCD34D', fontSize: 13, fontWeight: '800' },
  statusPillPending: {
    backgroundColor: 'rgba(245, 158, 11, 0.25)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  statusPillTextPending: { color: '#F59E0B', fontSize: 9, fontWeight: '900' },
  statusBannerSub: { color: theme.textSecondary, fontSize: 11, marginTop: 2, lineHeight: 15 },
  statusBannerActionPending: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    backgroundColor: '#F59E0B',
    paddingVertical: 8,
    borderRadius: 10,
  },
  statusBannerActionTextPending: { color: '#070A0F', fontSize: 11, fontWeight: '900' },

  driverStatusBannerRejected: {
    backgroundColor: theme.sosRedSurface,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.35)',
    borderRadius: 16,
    padding: 12,
    marginBottom: 12,
    gap: 10,
  },
  statusBannerIconRejected: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusBannerTitleRejected: { color: '#FCA5A5', fontSize: 13, fontWeight: '800' },
  statusPillRejected: {
    backgroundColor: 'rgba(239, 68, 68, 0.25)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  statusPillTextRejected: { color: '#EF4444', fontSize: 9, fontWeight: '900' },
  statusBannerActionRejected: {
    backgroundColor: '#EF4444',
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: 'center',
  },
  statusBannerActionTextRejected: { color: '#FFF', fontSize: 11, fontWeight: '900' },

  driverStatusBannerApproved: {
    backgroundColor: theme.badgeBg,
    borderWidth: 1,
    borderColor: theme.badgeBorder,
    borderRadius: 16,
    padding: 12,
    marginBottom: 12,
    gap: 10,
  },
  statusBannerIconApproved: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.badgeBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusBannerTitleApproved: { color: '#6EE7B7', fontSize: 13, fontWeight: '800' },
  statusPillApproved: {
    backgroundColor: 'rgba(16, 185, 129, 0.25)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  statusPillTextApproved: { color: '#10B981', fontSize: 9, fontWeight: '900' },
  statusBannerActionApproved: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    backgroundColor: '#10B981',
    paddingVertical: 8,
    borderRadius: 10,
  },
  statusBannerActionTextApproved: { color: '#070A0F', fontSize: 11, fontWeight: '900' },

  driverStatusBannerApply: {
    backgroundColor: theme.cardBg,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.25)',
    borderRadius: 16,
    padding: 12,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statusBannerIconApply: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.badgeBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusBannerTitleApply: { color: theme.textPrimary, fontSize: 13, fontWeight: '800' },
  applyArrowCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: theme.badgeBg,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Driver Application Modal
  applyModalSub: { color: theme.textSecondary, fontSize: 12, marginBottom: 14, lineHeight: 16 },
  applyInputLabel: { color: theme.textMuted, fontSize: 10, fontWeight: '800', marginTop: 10, marginBottom: 4, letterSpacing: 0.5 },
  applyTextInput: {
    backgroundColor: theme.background,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: theme.textPrimary,
    fontSize: 13,
    fontWeight: '700',
    borderWidth: 1,
    borderColor: theme.border,
  },
  applyCategoryRow: { flexDirection: 'row', gap: 6, marginTop: 4, marginBottom: 14 },
  applyCategoryChip: {
    flex: 1,
    backgroundColor: theme.background,
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.border,
  },
  applyCategoryChipActive: { backgroundColor: '#10B981', borderColor: '#10B981' },
  applyCategoryChipText: { color: theme.textSecondary, fontSize: 11, fontWeight: '700' },
  applyCategoryChipTextActive: { color: '#070A0F', fontWeight: '900' },
  applySubmitBtn: {
    backgroundColor: '#10B981',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 14,
    borderRadius: 14,
    marginTop: 10,
  },
  applySubmitBtnText: { color: theme.primary, fontSize: 14, fontWeight: '900' },
});
